const { examples, sections, bank, passages, stories } = window.GrammarLesson;
// shuffle utilities; preserve a new shuffled sequence per attempt
const shuffle=a=>{const b=[...a];for(let i=b.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[b[i],b[j]]=[b[j],b[i]]}return b};
const $=id=>document.getElementById(id);let saved=JSON.parse(localStorage.getItem('hangullab-progress')||'{"answered":0,"correct":0,"best":0,"seen":[]}');let currentView='home',session=[],pos=0,selected=null,checked=false,score=0;
function persist(){localStorage.setItem('hangullab-progress',JSON.stringify(saved));updateStats()}
function rankFor(n){return n>=90?'👑 TOPIK Master':n>=70?'🏆 Advanced':n>=40?'⭐ Intermediate':'🌱 Beginner'}
function updateStats(){const acc=saved.answered?Math.round(saved.correct/saved.answered*100):0;const pct=Math.min(100,Math.round(saved.seen.length/bank.length*100));$('correctStat').textContent=saved.correct;$('doneStat').textContent=saved.answered;$('accuracyStat').textContent=acc+'%';$('progressStat').textContent=pct+'%';$('progressBar').style.width=pct+'%';$('rankTop').textContent=rankFor(acc)}
function nav(){const items=[['home','⌂','Главная'],['theory','✦','Теория'],...sections.map(s=>[s[0],s[1],s[2]])];$('nav').innerHTML=items.map(x=>`<button class="${currentView===x[0]?'active':''}" onclick="${['home','theory'].includes(x[0])?`showView('${x[0]}')`:`openSection('${x[0]}')`}"><em>${x[1]}</em>${x[2]}</button>`).join('')}
function showView(v){currentView=v;nav();if(v==='theory')renderTheory();else renderHome()}
function renderHome(){$('content').innerHTML=`<section class="panel"><h2>Твоя учебная дорожка</h2><p class="sub">Выбирай короткий блок и закрепляй грамматику в контексте. В каждом задании есть разбор ответа.</p><div class="section-list">${sections.map(s=>`<div class="section-card" onclick="startSection('${s[0]}')"><div class="ico">${s[1]}</div><div><h3>${s[2]}</h3><p>${s[3]}</p></div><span class="count">${s[4]} заданий →</span></div>`).join('')}</div><p class="mini" style="margin-top:18px">Всего в тренажёре: ${bank.length} заданий · результат хранится в этом браузере</p></section>`}
function renderTheory(){$('content').innerHTML=`<section class="panel"><span class="tag">ГРАММАТИКА · TOPIK I–II</span><h2 style="margin-top:12px">-기는 하지만 / -기는 -지만</h2><p class="sub">«…конечно, но…», «хотя и…», «это правда, однако…»</p><div class="theory-grid"><div class="theory-box"><h3>💡 Значение</h3><p>Говорящий признаёт один факт, но сразу добавляет ограничение, противоположную оценку или неожиданный результат. Первая часть часто звучит как уступка: «да, X, но Y».</p></div><div class="theory-box"><h3>🧩 Формула</h3><div class="formula">основа + 기는 하지만</div><p>동사/형용사: 좋기는 하지만 · 먹기는 하지만<br>Разговорные варианты: 좋기는 한데, 좋긴 하지만.</p></div><div class="theory-box"><h3>⏱️ Прошедшее и акцент</h3><p><b>Основа + 기는 했지만:</b> 먹기는 했지만 — «поел, но…»</p><p><b>V/A기는 V/A-지만:</b> 읽기는 읽었지만 — повтор усиливает «делал-то делал, но…».</p></div><div class="theory-box"><h3>⚖️ Сравнение</h3><p><b>-지만</b> — обычное «но»: 싸지만 좋아요 (дёшево, но хорошо).</p><p><b>-기는 하지만</b> — первая часть подчёркнуто признаётся: 싸기는 하지만 품질이 아쉬워요.</p><p><b>-아/어도</b> — «даже если / хотя»: 바빠도 갈게요 (даже если занят, пойду).</p></div></div><div class="theory-box" style="margin-top:14px"><h3>🔧 Как образовать</h3><ul><li>Добавь 기는 к основе: 가다 → 가기는, 좋다 → 좋기는.</li><li>Продолжи 하지만; в разговоре часто говорят 한데/한데요 или 긴 하지만.</li><li>С прошедшим временем: 가기는 했지만, 좋기는 했지만. Также возможно 갔기는 하지만.</li><li>Для отрицания: 좋지는 않지만 (хотя не очень хорошо, зато…).</li></ul><p>Грамматичная конструкция не требует, чтобы обе части были строго противоположными; вторая часть может ограничивать ожидание первой.</p></div><div class="examples"><h3>Примеры в контексте</h3><table>${examples.map(e=>`<tr><td>${e[0]}</td><td>${e[1]}</td></tr>`).join('')}</table></div><div style="margin-top:22px"><button class="btn primary" onclick="startSection('warm')">Понял(а), к разминке →</button></div></section>`}
function openSection(id){currentView=id;nav();renderSectionIntro(id)}
function renderSectionIntro(id){const s=sections.find(x=>x[0]===id);$('content').innerHTML=`<section class="panel"><div class="ico" style="margin-bottom:14px">${s[1]}</div><h2>${s[2]}</h2><p class="sub">${s[3]}. Вопросы перемешиваются при каждом запуске; разбор покажет, почему выбранная форма подходит.</p><div class="theory-box"><b>${s[4]} заданий</b><p>Можно отвечать в комфортном темпе. После проверки увидишь правильный вариант, объяснение и разбор отвлекающих ответов.</p></div><button class="btn primary" style="margin-top:18px" onclick="startSection('${id}')">Начать блок →</button></section>`}
function startSection(id){currentView=id;nav();session=shuffle(bank.filter(q=>q.section===id));pos=0;selected=null;checked=false;score=0;renderQuestion()}
function renderQuestion(){if(pos>=session.length){renderComplete();return}selected=null;checked=false;const q=session[pos];let seen='';if(q.passage!==undefined)seen=`<div class="passage"><b>${passages[q.passage].title}</b><br>${passages[q.passage].text}</div>`;if(q.story!==undefined)seen=`<div class="passage"><b>${stories[q.story].title}</b><br>${stories[q.story].text}</div>`;const options=shuffle(q.opts.map((t,i)=>({t,i})));q.displayOptions=options;$('content').innerHTML=`<section class="lesson"><div class="lesson-top"><span>${sections.find(s=>s[0]===q.section)[1]} ${sections.find(s=>s[0]===q.section)[2]}</span><span>Вопрос ${pos+1} / ${session.length}</span></div><div class="bar"><i style="width:${Math.round(pos/session.length*100)}%"></i></div>${seen}<div class="qtext">${q.prompt}</div><div class="choices">${options.map((o,i)=>`<button class="choice" id="opt${i}" onclick="choose(${i})">${o.t}</button>`).join('')}</div><div id="feedback"></div><div class="lesson-actions"><button class="btn soft" onclick="showView('home')">← Выйти</button><button class="btn primary" id="checkBtn" onclick="checkAnswer()">Проверить</button></div></section>`}
function choose(i){if(checked)return;selected=i;document.querySelectorAll('.choice').forEach((b,j)=>b.classList.toggle('selected',j===i))}
function checkAnswer(){if(checked){pos++;renderQuestion();return}if(selected===null){toast('Выбери вариант ответа');return}checked=true;const q=session[pos],picked=q.displayOptions[selected].i,ok=picked===q.ans;if(ok)score++;saved.answered++;if(ok)saved.correct++;if(!saved.seen.includes(q.prompt))saved.seen.push(q.prompt);persist();q.displayOptions.forEach((o,i)=>{const b=$('opt'+i);if(o.i===q.ans)b.classList.add('correct');else if(i===selected)b.classList.add('wrong')});const other=q.wrong||'Этот вариант меняет смысл или грамматическую связь исходной фразы.';$('feedback').innerHTML=`<div class="feedback ${ok?'good':'bad'}"><strong>${ok?'Верно! Отличное наблюдение ✨':'Почти — разберём спокойно'}</strong><b>Правильный ответ:</b> ${q.opts[q.ans]}<br>${q.why}<br><span style="opacity:.86"><b>Почему не остальные:</b> ${other}</span></div>`;$('checkBtn').textContent=pos===session.length-1?'Завершить блок':'Следующий вопрос →';$('checkBtn').onclick=()=>{pos++;renderQuestion()}}
function renderComplete(){const pct=Math.round(score/session.length*100);saved.best=Math.max(saved.best,pct);persist();const medal=pct>=90?'👑':pct>=70?'🏆':pct>=40?'⭐':'🌱';$('content').innerHTML=`<section class="panel complete"><div class="trophy">${medal}</div><span class="tag">БЛОК ЗАВЕРШЁН</span><h2>Ты продвинулся!</h2><p>В этом раунде: <b>${score} из ${session.length}</b> правильных · точность <b>${pct}%</b>.<br>${pct>=80?'Отлично чувствуешь оттенок уступки.':pct>=50?'Хороший темп — повторение закрепит разницу.':'Теория и примеры помогут собрать конструкцию уверенно.'}</p><div class="bar" style="max-width:420px;margin:20px auto"><i style="width:${pct}%"></i></div><button class="btn primary" onclick="startSection('${currentView}')">Пройти ещё раз ↻</button> <button class="btn soft" onclick="showView('home')">К учебной дорожке</button></section>`}
function toast(t){$('toast').textContent=t;$('toast').classList.add('show');setTimeout(()=>$('toast').classList.remove('show'),1800)}
nav();updateStats();renderHome();
